import type {
  Incident,
  EvidenceFile,
  Witness,
  PoliceReport,
  IntegrityLogRow,
} from './database.types';
import { categoryMeta, evidenceKindMeta, relationshipMeta, reportStatusMeta } from '@/theme/categories';

/** Escape user text for safe HTML embedding. */
function esc(v: unknown): string {
  if (v == null) return '';
  return String(v)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function fmt(date?: string | null): string {
  if (!date) return '—';
  const d = new Date(date);
  return isNaN(d.getTime()) ? esc(date) : d.toLocaleString();
}

const STYLES = `
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #11202F; margin: 0; padding: 0; }
    .page { padding: 40px 44px; }
    h1 { font-size: 24px; margin: 0 0 2px; }
    h2 { font-size: 15px; text-transform: uppercase; letter-spacing: 1px; color: #2C7A74;
         border-bottom: 2px solid #E2E8F0; padding-bottom: 6px; margin: 28px 0 12px; }
    .sub { color: #64748B; font-size: 12px; margin: 0 0 4px; }
    .meta { color: #94A3B8; font-size: 11px; }
    .card { border: 1px solid #E2E8F0; border-radius: 8px; padding: 12px 14px; margin: 0 0 10px; }
    .card .title { font-weight: 700; font-size: 14px; }
    .row { display: flex; justify-content: space-between; gap: 12px; font-size: 12px; padding: 2px 0; }
    .label { color: #64748B; }
    .pill { display: inline-block; padding: 2px 9px; border-radius: 999px; font-size: 11px; font-weight: 600; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { text-align: left; color: #64748B; border-bottom: 1px solid #CBD5E1; padding: 6px 6px; font-weight: 600; }
    td { border-bottom: 1px solid #EEF2F6; padding: 6px 6px; vertical-align: top; }
    .mono { font-family: 'Courier New', monospace; font-size: 10px; word-break: break-all; }
    .disclaimer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #E2E8F0;
                  color: #94A3B8; font-size: 10px; line-height: 1.5; }
    .brand { color: #2C7A74; font-weight: 700; }
  </style>
`;

function shell(title: string, subtitle: string, body: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8">${STYLES}</head><body><div class="page">
    <div><span class="brand">🛡️ EvidenceVault</span></div>
    <h1>${esc(title)}</h1>
    <p class="sub">${esc(subtitle)}</p>
    <p class="meta">Generated ${new Date().toLocaleString()}</p>
    ${body}
    <div class="disclaimer">
      This document was generated by EvidenceVault from records maintained by the account holder.
      EvidenceVault is a documentation tool and does not verify the truth of recorded statements.
      File integrity hashes (SHA-256) are captured at the time each file is added to the vault.
    </div>
  </div></body></html>`;
}

// ---------- Integrity report (Phase 3) ----------
export function integrityReportHtml(evidence: EvidenceFile[], logs: IntegrityLogRow[]): string {
  const rows = evidence
    .map(
      (e) => `<tr>
        <td>${esc(e.caption || e.original_filename || evidenceKindMeta(e.kind).label)}</td>
        <td>${esc(evidenceKindMeta(e.kind).label)}</td>
        <td>${fmt(e.captured_at)}</td>
        <td class="mono">${esc(e.sha256)}</td>
      </tr>`,
    )
    .join('');

  const logRows = logs
    .slice(0, 500)
    .map(
      (l) => `<tr>
        <td>${fmt(l.occurred_at)}</td>
        <td>${esc(l.entity_type)}</td>
        <td>${esc(l.action)}</td>
        <td class="mono">${esc(l.sha256_after ?? l.sha256_before ?? '')}</td>
      </tr>`,
    )
    .join('');

  const body = `
    <h2>Evidence integrity (${evidence.length})</h2>
    <table><thead><tr><th>Item</th><th>Type</th><th>Captured</th><th>SHA-256</th></tr></thead>
      <tbody>${rows || '<tr><td colspan="4">No evidence.</td></tr>'}</tbody></table>
    <h2>Chain-of-custody log (${logs.length})</h2>
    <table><thead><tr><th>When</th><th>Entity</th><th>Action</th><th>Hash</th></tr></thead>
      <tbody>${logRows || '<tr><td colspan="4">No events.</td></tr>'}</tbody></table>`;
  return shell('Evidence Integrity Report', 'Digital chain of custody', body);
}

// ---------- Evidence index (Phase 5) ----------
export function evidenceIndexHtml(evidence: EvidenceFile[]): string {
  const rows = evidence
    .map(
      (e, i) => `<tr>
        <td>${i + 1}</td>
        <td>${esc(e.caption || e.original_filename || '—')}</td>
        <td>${esc(evidenceKindMeta(e.kind).label)}</td>
        <td>${fmt(e.captured_at)}</td>
        <td>${(e.size_bytes / 1024).toFixed(0)} KB</td>
      </tr>`,
    )
    .join('');
  const body = `<h2>Evidence index (${evidence.length})</h2>
    <table><thead><tr><th>#</th><th>Description</th><th>Type</th><th>Captured</th><th>Size</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="5">No evidence.</td></tr>'}</tbody></table>`;
  return shell('Evidence Index', 'All evidence on file', body);
}

// ---------- Witness list (Phase 5) ----------
export function witnessListHtml(witnesses: Witness[]): string {
  const cards = witnesses
    .map(
      (w) => `<div class="card">
        <div class="title">${esc(w.name)}</div>
        <div class="row"><span class="label">Phone</span><span>${esc(w.phone) || '—'}</span></div>
        <div class="row"><span class="label">Email</span><span>${esc(w.email) || '—'}</span></div>
        <div class="row"><span class="label">Date of event</span><span>${esc(w.event_date) || '—'}</span></div>
        ${w.written_statement ? `<div class="row"><span class="label">Statement</span></div><div>${esc(w.written_statement)}</div>` : ''}
      </div>`,
    )
    .join('');
  const body = `<h2>Witnesses (${witnesses.length})</h2>${cards || '<p>No witnesses.</p>'}`;
  return shell('Witness List', 'People who witnessed events', body);
}

// ---------- Police report history (Phase 5) ----------
export function policeReportHistoryHtml(reports: PoliceReport[]): string {
  const rows = reports
    .map(
      (r) => `<tr>
        <td>${esc(r.report_number) || '—'}</td>
        <td>${esc(r.agency) || '—'}</td>
        <td>${esc(r.officer_name) || '—'}${r.officer_badge ? ` (#${esc(r.officer_badge)})` : ''}</td>
        <td>${esc(r.filed_at) || '—'}</td>
        <td>${esc(reportStatusMeta(r.status).label)}</td>
      </tr>`,
    )
    .join('');
  const body = `<h2>Police report history (${reports.length})</h2>
    <table><thead><tr><th>Report #</th><th>Agency</th><th>Officer</th><th>Filed</th><th>Status</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="5">No reports.</td></tr>'}</tbody></table>`;
  return shell('Police Report History', 'All reports filed', body);
}

// ---------- Timeline report (Phase 5) ----------
export function timelineReportHtml(incidents: Incident[], evidence: EvidenceFile[]): string {
  const items = [
    ...incidents.map((i) => ({ at: i.occurred_at, label: `Incident — ${i.title}`, sub: categoryMeta(i.category).label })),
    ...evidence.map((e) => ({
      at: e.captured_at,
      label: `Evidence — ${e.caption || e.original_filename || evidenceKindMeta(e.kind).label}`,
      sub: evidenceKindMeta(e.kind).label,
    })),
  ].sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime());

  const rows = items
    .map((it) => `<tr><td>${fmt(it.at)}</td><td>${esc(it.label)}</td><td>${esc(it.sub)}</td></tr>`)
    .join('');
  const body = `<h2>Chronological timeline (${items.length} entries)</h2>
    <table><thead><tr><th>When</th><th>Event</th><th>Type</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="3">No entries.</td></tr>'}</tbody></table>`;
  return shell('Timeline Report', 'Events and evidence in chronological order', body);
}

// ---------- Full case file (Phase 5) ----------
export interface CaseFileData {
  incidents: Incident[];
  evidence: EvidenceFile[];
  witnesses: Witness[];
  reports: PoliceReport[];
  logs: IntegrityLogRow[];
}

export function caseFileHtml(data: CaseFileData): string {
  const incidentCards = data.incidents
    .map(
      (i) => `<div class="card">
        <div class="title">${esc(i.title)}</div>
        <div class="row"><span class="label">Category</span><span>${esc(categoryMeta(i.category).label)}</span></div>
        <div class="row"><span class="label">When</span><span>${fmt(i.occurred_at)}</span></div>
        ${i.location_label ? `<div class="row"><span class="label">Location</span><span>${esc(i.location_label)}</span></div>` : ''}
        ${i.notes ? `<div class="row"><span class="label">Notes</span></div><div>${esc(i.notes)}</div>` : ''}
        ${i.emotional_impact ? `<div class="row"><span class="label">Impact</span></div><div>${esc(i.emotional_impact)}</div>` : ''}
        ${i.follow_up_actions ? `<div class="row"><span class="label">Follow-up</span></div><div>${esc(i.follow_up_actions)}</div>` : ''}
      </div>`,
    )
    .join('');

  const evidenceRows = data.evidence
    .map(
      (e) => `<tr><td>${esc(e.caption || e.original_filename || '—')}</td><td>${esc(evidenceKindMeta(e.kind).label)}</td>
        <td>${fmt(e.captured_at)}</td><td class="mono">${esc(e.sha256.slice(0, 24))}…</td></tr>`,
    )
    .join('');

  const witnessCards = data.witnesses
    .map(
      (w) => `<div class="card"><div class="title">${esc(w.name)}</div>
        <div class="row"><span class="label">Contact</span><span>${esc([w.phone, w.email].filter(Boolean).join(' · ')) || '—'}</span></div>
        ${w.written_statement ? `<div>${esc(w.written_statement)}</div>` : ''}</div>`,
    )
    .join('');

  const reportRows = data.reports
    .map(
      (r) => `<tr><td>${esc(r.report_number) || '—'}</td><td>${esc(r.agency) || '—'}</td>
        <td>${esc(r.filed_at) || '—'}</td><td>${esc(reportStatusMeta(r.status).label)}</td></tr>`,
    )
    .join('');

  const body = `
    <h2>Summary</h2>
    <table><tbody>
      <tr><td>Incidents</td><td>${data.incidents.length}</td></tr>
      <tr><td>Evidence items</td><td>${data.evidence.length}</td></tr>
      <tr><td>Witnesses</td><td>${data.witnesses.length}</td></tr>
      <tr><td>Police reports</td><td>${data.reports.length}</td></tr>
      <tr><td>Integrity events logged</td><td>${data.logs.length}</td></tr>
    </tbody></table>

    <h2>Incidents (${data.incidents.length})</h2>
    ${incidentCards || '<p>None.</p>'}

    <h2>Evidence (${data.evidence.length})</h2>
    <table><thead><tr><th>Description</th><th>Type</th><th>Captured</th><th>SHA-256</th></tr></thead>
    <tbody>${evidenceRows || '<tr><td colspan="4">None.</td></tr>'}</tbody></table>

    <h2>Witnesses (${data.witnesses.length})</h2>
    ${witnessCards || '<p>None.</p>'}

    <h2>Police reports (${data.reports.length})</h2>
    <table><thead><tr><th>Report #</th><th>Agency</th><th>Filed</th><th>Status</th></tr></thead>
    <tbody>${reportRows || '<tr><td colspan="4">None.</td></tr>'}</tbody></table>`;

  return shell('Case File', 'Complete record export', body);
}
